theme: jekyll-theme-cayman
baseurl: /c97ace4c8fef2cee8fa0f3c9f52aab18dbd4f42438afe362ffb8f75ce4c04b84/
title: Score Rearrangement
description: "Temporary site for 'piano score rearrangement' paper"
google_analytics: G-21TSYC4LPC
